---
title: "Reconstruct MS1 spectra"
author: "Michael Witting"
date: "22 11 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read Cluster and Peak data

```{r cars}
# load required libraries
library(genedataRutils)
library(MSnbase)
library(tidyverse)

# files with MS1 data grouped only with HMDB as filter
peak_file <- system.file("extdata/Pesticides/20191108_Pesticides_HMDB_Peaks.gda", package = "genedataRutils")
cluster_file <- system.file("extdata/Pesticides/20191108_Pesticides_HMDB_Cluster.gda", package = "genedataRutils")

# read MS1 data
read_gda_file(peak_file, prefix = "hmdb_peak_")
read_gda_file(cluster_file, prefix = "hmdb_cluster_")

# files with MS1 data grouped only with HMDB & PubChem as filter
peak_file <- system.file("extdata/Pesticides/20191108_Pesticides_HMDBPubChem_Peaks.gda", package = "genedataRutils")
cluster_file <- system.file("extdata/Pesticides/20191108_Pesticides_HMDBPubchem_Cluster.gda", package = "genedataRutils")

# read MS1 data
read_gda_file(peak_file, prefix = "hmdbpubchem_peak_")
read_gda_file(cluster_file, prefix = "hmdbpubchem_cluster_")
```

## Reconstruct MS1 spectra

TODO: Subset data to specific range for vignette

```{r}
# isolate only the cluster of Fluopicolide
filtered_cluster_row_anno <- hmdbpubchem_cluster_row_anno[which(abs(hmdbpubchem_cluster_row_anno$`m/z` - 382.9727065) < 0.005),]
filtered_peak_row_anno <- hmdbpubchem_peak_row_anno[which(hmdbpubchem_peak_row_anno$`Cluster [C]` == as.numeric(str_extract(row.names(filtered_cluster_row_anno), "\\d+"))),]
```


```{r}
# reconstruct MS1 spectra for Fluopicolide
library(foreach)
library(doParallel)

# create cluster for parallel processing
cl <- parallel::makeCluster(6)
registerDoParallel(cl)

ms1_spectra <- recon_iso_pattern(filtered_peak_row_anno, filtered_cluster_row_anno, hmdbpubchem_peak_ms_data)

stopCluster(cl)
```

```{r}
comb_ms1_spec <- combineSpectra(ms1_spectra, fcol = "CLUSTER_ID", intensityFun = base::sum, mzd = 0.005)
plot(comb_ms1_spec[[1]])
```

